// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// atomKummer
double atomKummer(double x, double a, double b, double relTol);
RcppExport SEXP _pestim_atomKummer(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP relTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type relTol(relTolSEXP);
    rcpp_result_gen = Rcpp::wrap(atomKummer(x, a, b, relTol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pestim_atomKummer", (DL_FUNC) &_pestim_atomKummer, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_pestim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
