// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Kummer
NumericVector Kummer(const NumericVector& z, const NumericVector& a, const NumericVector& b, const double relTol);
RcppExport SEXP _pestim_Kummer(SEXP zSEXP, SEXP aSEXP, SEXP bSEXP, SEXP relTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type relTol(relTolSEXP);
    rcpp_result_gen = Rcpp::wrap(Kummer(z, a, b, relTol));
    return rcpp_result_gen;
END_RCPP
}
// pKummer
Rcpp::NumericVector pKummer(const Rcpp::NumericVector& z, const Rcpp::NumericVector& a, const Rcpp::NumericVector& b, double relTol);
RcppExport SEXP _pestim_pKummer(SEXP zSEXP, SEXP aSEXP, SEXP bSEXP, SEXP relTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type relTol(relTolSEXP);
    rcpp_result_gen = Rcpp::wrap(pKummer(z, a, b, relTol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pestim_Kummer", (DL_FUNC) &_pestim_Kummer, 4},
    {"_pestim_pKummer", (DL_FUNC) &_pestim_pKummer, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_pestim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
