# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kummer <- function(z, a, b, relTol, err) {
    .Call('_pestim_Kummer', PACKAGE = 'pestim', z, a, b, relTol, err)
}

pKummer <- function(z, a, b, relTol, err) {
    .Call('_pestim_pKummer', PACKAGE = 'pestim', z, a, b, relTol, err)
}

